import { Inter } from "next/font/google"
import "./globals.css";
import Providers from "./providers";
import { SignInProvider } from "@/context/signInContext";
import { UserProvider } from "@/context/userContext";
import { FavoritesProvider } from "@/context/favoriteContext";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import GetFavourites from "./components/GetFavourites";
import { XIProvider } from "@/context/xiContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

export const metadata = {
  title: "GOALIQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
     className={`${inter.variable}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <SignInProvider>
            <UserProvider>
              <FavoritesProvider>
                <XIProvider>
                  {children}
                  <ToastContainer
                    position="top-right"
                    autoClose={3000}
                    theme="dark"
                  />
                  <GetFavourites />
                </XIProvider>
              </FavoritesProvider>
            </UserProvider>
          </SignInProvider>
        </Providers>
      </body>
    </html>
  );
}
