import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { SignInProvider } from "@/context/signInContext";
import { UserProvider } from "@/context/userContext";
import { FavoritesProvider } from "@/context/favoriteContext";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import GetFavourites from "./components/GetFavourites";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "GOALIQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    //  className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <Providers>
          <SignInProvider>
            <UserProvider>
              <FavoritesProvider>
                {children}
                <ToastContainer
                  position="top-right"
                  autoClose={3000}
                  theme="dark"
                />
                <GetFavourites />
              </FavoritesProvider>
            </UserProvider>
          </SignInProvider>
        </Providers>
      </body>
    </html>
  );
}
