import { Inter } from "next/font/google"
import "./globals.css"
import Providers from "./providers"
import { SignInProvider } from "@/context/signInContext"
import { UserProvider } from "@/context/userContext"
import { FavoritesProvider } from "@/context/favoriteContext"
import { ToastProvider } from "./components/ToastProvider"
import SWRProvider from "./components/SWRProvider"
import GetFavourites from "./components/GetFavourites"
import { XIProvider } from "@/context/xiContext"
import ThemeWrapper from "./components/ThemeWrapper"
import { SidebarProvider } from "@/context/sidebarContext"
import { ThemeProvider } from "@/context/themeContext"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

export const metadata = {
  title: "GOALIQ",
  description: "Generated by create next app",
}

// Server component: no hooks and no function props here.
// SWR config lives in SWRProvider (a client component).
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `try{var t=localStorage.getItem('goaliq-theme');if(t!=='light'&&t!=='dark')t='dark';var r=document.documentElement;r.classList.add(t);r.setAttribute('data-theme',t)}catch(e){}`,
          }}
        />
      </head>
      <body className={`${inter.variable} font-sans`}>
        {/* ToastProvider is outermost so SWRProvider (and everything below)
            can call useToast(). SWRProvider is next so ALL useSWR hooks in the
            app get the shared fetcher and retry rules. */}
        <ToastProvider>
          <SWRProvider>
            <SignInProvider>
              {/* SessionProvider MUST wrap UserProvider */}
              <SidebarProvider>
                <Providers>
                  <UserProvider>
                    <ThemeProvider>
                      <FavoritesProvider>
                        <XIProvider>
                          <ThemeWrapper>
                            <GetFavourites />
                            {children}
                          </ThemeWrapper>
                        </XIProvider>
                      </FavoritesProvider>
                    </ThemeProvider>
                  </UserProvider>
                </Providers>
              </SidebarProvider>
            </SignInProvider>
          </SWRProvider>
        </ToastProvider>
      </body>
    </html>
  )
}